

LOCK TABLES `privilegios` WRITE;
/*!40000 ALTER TABLE `privilegios` DISABLE KEYS */;
INSERT INTO `privilegios` VALUES (1,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'TABLERO',NULL,NULL);
INSERT INTO `privilegios` VALUES (2,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'NOTIFICAR_PAGO',NULL,NULL);
INSERT INTO `privilegios` VALUES (3,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'HISTORIAL_PAGOS',NULL,NULL);
INSERT INTO `privilegios` VALUES (4,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'HISTORIAL_PAGOS_INMUEBLE',NULL,NULL);
INSERT INTO `privilegios` VALUES (5,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'VERIFICAR_PAGO',NULL,NULL);
INSERT INTO `privilegios` VALUES (6,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'ABRIR_TICKET',NULL,NULL);
INSERT INTO `privilegios` VALUES (7,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'VER_TICKET',NULL,NULL);
INSERT INTO `privilegios` VALUES (8,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'ASIGNAR_TICKET',NULL,NULL);
INSERT INTO `privilegios` VALUES (9,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'ACEPTAR_TICKET',NULL,NULL);
INSERT INTO `privilegios` VALUES (10,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'ATENDER_TICKET',NULL,NULL);
INSERT INTO `privilegios` VALUES (11,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'RECHAZAR_TICKET',NULL,NULL);
INSERT INTO `privilegios` VALUES (12,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'CERRAR_TICKET',NULL,NULL);
INSERT INTO `privilegios` VALUES (13,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'CANCELAR_TICKET',NULL,NULL);
INSERT INTO `privilegios` VALUES (14,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'LISTA_SOCIOS',NULL,NULL);
INSERT INTO `privilegios` VALUES (15,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'ESTADO_FINANCIERO_INMUEBLE',NULL,NULL);
INSERT INTO `privilegios` VALUES (16,'2019-02-27 20:51:39','2019-02-27 20:51:39',_binary '\0',NULL,'ESTADO_FINANCIERO_COLONIA',NULL,NULL);
INSERT INTO `privilegios` VALUES (17,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0',NULL,'ESTADO_FINANCIERO_ZONA',NULL,NULL);
INSERT INTO `privilegios` VALUES (18,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0',NULL,'GESTIONAR_COLONIA',NULL,NULL);
INSERT INTO `privilegios` VALUES (19,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0',NULL,'GESTIONAR_ZONA',NULL,NULL);
INSERT INTO `privilegios` VALUES (20,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0',NULL,'GESTIONAR_INMUEBLES',NULL,NULL);
INSERT INTO `privilegios` VALUES (21,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0',NULL,'GESTIONAR_SERVICIOS',NULL,NULL);
INSERT INTO `privilegios` VALUES (22,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0',NULL,'GESTIONAR_PREGUNTAS',NULL,NULL);
INSERT INTO `privilegios` VALUES (23,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0',NULL,'GESTIONAR_SOCIO_BI',NULL,NULL);
INSERT INTO `privilegios` VALUES (24,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0',NULL,'GESTIONAR_ADMIN_BI',NULL,NULL);
INSERT INTO `privilegios` VALUES (25,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0',NULL,'GESTIONAR_ADMIN_ZONA',NULL,NULL);
INSERT INTO `privilegios` VALUES (26,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0',NULL,'GESTIONAR_PROVEEDOR',NULL,NULL);
INSERT INTO `privilegios` VALUES (27,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0',NULL,'GESTIONAR_ADMIN_CORP',NULL,NULL);
INSERT INTO `privilegios` VALUES (28,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0',NULL,'REPORTES',NULL,NULL);
INSERT INTO `privilegios` VALUES (29,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0',NULL,'REPORTE_MOROSOS',NULL,NULL);
/*!40000 ALTER TABLE `privilegios` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `roles` WRITE;
/*!40000 ALTER TABLE `roles` DISABLE KEYS */;
INSERT INTO `roles` VALUES (30,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0','Proveedor','ROLE_PROVEEDOR',NULL,NULL);
INSERT INTO `roles` VALUES (31,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0','Condómino','ROLE_SOCIO_BI',NULL,NULL);
INSERT INTO `roles` VALUES (32,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0','Administrador de bien inmueble','ROLE_ADMIN_BI',NULL,NULL);
INSERT INTO `roles` VALUES (33,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0','Director de área','ROLE_ADMIN_ZONA',NULL,NULL);
INSERT INTO `roles` VALUES (34,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0','Director corporativo','ROLE_ADMIN_CORP',NULL,NULL);
INSERT INTO `roles` VALUES (35,'2019-02-27 20:51:40','2019-02-27 20:51:40',_binary '\0','Contador','ROLE_CONTADOR',NULL,NULL);
/*!40000 ALTER TABLE `roles` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `roles_privilegios` WRITE;
/*!40000 ALTER TABLE `roles_privilegios` DISABLE KEYS */;
INSERT INTO `roles_privilegios` VALUES (30,9);
INSERT INTO `roles_privilegios` VALUES (30,7);
INSERT INTO `roles_privilegios` VALUES (30,10);
INSERT INTO `roles_privilegios` VALUES (30,11);
INSERT INTO `roles_privilegios` VALUES (31,1);
INSERT INTO `roles_privilegios` VALUES (31,2);
INSERT INTO `roles_privilegios` VALUES (31,3);
INSERT INTO `roles_privilegios` VALUES (31,7);
INSERT INTO `roles_privilegios` VALUES (31,6);
INSERT INTO `roles_privilegios` VALUES (31,13);
INSERT INTO `roles_privilegios` VALUES (32,8);
INSERT INTO `roles_privilegios` VALUES (32,7);
INSERT INTO `roles_privilegios` VALUES (32,12);
INSERT INTO `roles_privilegios` VALUES (32,13);
INSERT INTO `roles_privilegios` VALUES (32,23);
INSERT INTO `roles_privilegios` VALUES (32,5);
INSERT INTO `roles_privilegios` VALUES (32,3);
INSERT INTO `roles_privilegios` VALUES (32,18);
INSERT INTO `roles_privilegios` VALUES (32,20);
INSERT INTO `roles_privilegios` VALUES (32,21);
INSERT INTO `roles_privilegios` VALUES (32,22);
INSERT INTO `roles_privilegios` VALUES (32,23);
INSERT INTO `roles_privilegios` VALUES (32,24);
INSERT INTO `roles_privilegios` VALUES (32,26);
INSERT INTO `roles_privilegios` VALUES (32,16);
INSERT INTO `roles_privilegios` VALUES (33,8);
INSERT INTO `roles_privilegios` VALUES (33,7);
INSERT INTO `roles_privilegios` VALUES (33,12);
INSERT INTO `roles_privilegios` VALUES (33,13);
INSERT INTO `roles_privilegios` VALUES (33,23);
INSERT INTO `roles_privilegios` VALUES (33,5);
INSERT INTO `roles_privilegios` VALUES (33,3);
INSERT INTO `roles_privilegios` VALUES (33,18);
INSERT INTO `roles_privilegios` VALUES (33,20);
INSERT INTO `roles_privilegios` VALUES (33,21);
INSERT INTO `roles_privilegios` VALUES (33,22);
INSERT INTO `roles_privilegios` VALUES (33,23);
INSERT INTO `roles_privilegios` VALUES (33,24);
INSERT INTO `roles_privilegios` VALUES (33,26);
INSERT INTO `roles_privilegios` VALUES (33,16);
INSERT INTO `roles_privilegios` VALUES (33,17);
INSERT INTO `roles_privilegios` VALUES (34,8);
INSERT INTO `roles_privilegios` VALUES (34,7);
INSERT INTO `roles_privilegios` VALUES (34,12);
INSERT INTO `roles_privilegios` VALUES (34,13);
INSERT INTO `roles_privilegios` VALUES (34,23);
INSERT INTO `roles_privilegios` VALUES (34,5);
INSERT INTO `roles_privilegios` VALUES (34,3);
INSERT INTO `roles_privilegios` VALUES (34,18);
INSERT INTO `roles_privilegios` VALUES (34,20);
INSERT INTO `roles_privilegios` VALUES (34,21);
INSERT INTO `roles_privilegios` VALUES (34,22);
INSERT INTO `roles_privilegios` VALUES (34,23);
INSERT INTO `roles_privilegios` VALUES (34,24);
INSERT INTO `roles_privilegios` VALUES (34,26);
INSERT INTO `roles_privilegios` VALUES (34,16);
INSERT INTO `roles_privilegios` VALUES (34,17);
INSERT INTO `roles_privilegios` VALUES (34,19);
INSERT INTO `roles_privilegios` VALUES (34,25);
INSERT INTO `roles_privilegios` VALUES (34,27);
INSERT INTO `roles_privilegios` VALUES (34,28);
INSERT INTO `roles_privilegios` VALUES (34,2);
INSERT INTO `roles_privilegios` VALUES (34,3);
INSERT INTO `roles_privilegios` VALUES (34,4);
INSERT INTO `roles_privilegios` VALUES (34,5);
/*!40000 ALTER TABLE `roles_privilegios` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `tipos_ticket` WRITE;
/*!40000 ALTER TABLE `tipos_ticket` DISABLE KEYS */;
INSERT INTO `tipos_ticket` VALUES (1,'2019-02-27 20:51:40','2019-02-27 20:51:40','Administrativo',NULL,NULL);
INSERT INTO `tipos_ticket` VALUES (2,'2019-02-27 20:51:40','2019-02-27 20:51:40','Solicitud de servicios',NULL,NULL);
INSERT INTO `tipos_ticket` VALUES (3,'2019-02-27 20:51:40','2019-02-27 20:51:40','Quejas y sugerencias',NULL,NULL);
/*!40000 ALTER TABLE `tipos_ticket` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `usuarios` WRITE;
/*!40000 ALTER TABLE `usuarios` DISABLE KEYS */;
INSERT INTO `usuarios` VALUES (36,'2019-02-27 20:51:40','2019-02-27 20:51:40',true,'','Corporativo','$2a$10$iRoO/dhcQ6wFuv0d79M4zu2aSWUuhYBAe3Lxt.y5XdqDpxBKBJnq.','correo@gmail.com',NULL,NULL,100.29,_binary '\0',_binary '\0',_binary '\0','343242453556464',NULL,NULL,NULL,NULL,NULL,'Administrador','123456',NULL,NULL,NULL,NULL,NULL,'admin_corp',NULL,NULL,NULL,NULL,NULL,NULL);
/*!40000 ALTER TABLE `usuarios` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `usuarios_roles` WRITE;
/*!40000 ALTER TABLE `usuarios_roles` DISABLE KEYS */;
INSERT INTO `usuarios_roles` VALUES (36,34);
/*!40000 ALTER TABLE `usuarios_roles` ENABLE KEYS */;
UNLOCK TABLES;

insert into mensajes_contacto_estatus (id_mensajes_contacto_estatus, nombre, idioma, activo) values(1, 'No Atendido', 'es', true);
insert into mensajes_contacto_estatus (id_mensajes_contacto_estatus, nombre, idioma, activo) values(2, 'En Proceso', 'es', true);
insert into mensajes_contacto_estatus (id_mensajes_contacto_estatus, nombre, idioma, activo) values(3, 'Atendido', 'es', true);
insert into mensajes_contacto_estatus (id_mensajes_contacto_estatus, nombre, idioma, activo) values(4, 'To do', 'en', true);
insert into mensajes_contacto_estatus (id_mensajes_contacto_estatus, nombre, idioma, activo) values(5, 'In Progress', 'en', true);
insert into mensajes_contacto_estatus (id_mensajes_contacto_estatus, nombre, idioma, activo) values(6, 'Done', 'en', true);

insert into sectores (id_sector, nombre, idioma) values(1, 'Condiminios', 'es');
insert into sectores (id_sector, nombre, idioma) values(2, 'Corporativos', 'es');
insert into sectores (id_sector, nombre, idioma) values(3, 'Centros Comerciales', 'es');
insert into sectores (id_sector, nombre, idioma) values(4, 'Hoteles', 'es');
insert into sectores (id_sector, nombre, idioma) values(5, 'Almacenes', 'es');
insert into sectores (id_sector, nombre, idioma) values(6, 'Inmuebles', 'es');
insert into sectores (id_sector, nombre, idioma) values(7, 'Condominiums', 'en');
insert into sectores (id_sector, nombre, idioma) values(8, 'Corporate', 'en');
insert into sectores (id_sector, nombre, idioma) values(9, 'Malls', 'en');
insert into sectores (id_sector, nombre, idioma) values(10, 'Hotels', 'en');
insert into sectores (id_sector, nombre, idioma) values(11, 'Warehouses', 'en');
insert into sectores (id_sector, nombre, idioma) values(12, 'Immovables', 'en');


insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`) values (1, 'contacto.ags@gesco-pls.com', 'contacto.corpo@gesco-pls.com','Aguascalientes');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (2, 'contacto.corpo@gesco-pls.com', null, 'Baja California');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (3, 'contacto.corpo@gesco-pls.com', null, 'Baja California Sur');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (4, 'contacto.corpo@gesco-pls.com', null, 'Campeche');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (5, 'contacto.corpo@gesco-pls.com', null, 'Coahuila');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (6, 'contacto.corpo@gesco-pls.com', null, 'Colima');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (7, 'contacto.corpo@gesco-pls.com', null, 'Chiapas');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (8, 'contacto.corpo@gesco-pls.com', null, 'Chihuahua');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (09, 'contacto.ags@gesco-pls.com', null, 'Ciudad de México');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (10, 'contacto.corpo@gesco-pls.com', null, 'Durango');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (11, 'contacto.corpo@gesco-pls.com', null, 'Guanajuato');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (12, 'contacto.corpo@gesco-pls.com', null, 'Guerrero');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (13, 'contacto.corpo@gesco-pls.com', null, 'Hidalgo');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (14, 'contacto.corpo@gesco-pls.com', null, 'Jalisco');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (15, 'contacto.corpo@gesco-pls.com', null, 'México');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (16, 'contacto.corpo@gesco-pls.com', null, 'Michoacán');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (17, 'contacto.corpo@gesco-pls.com', null, 'Morelos');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (18, 'contacto.corpo@gesco-pls.com', null, 'Nayarit');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (19, 'contacto.corpo@gesco-pls.com', null, 'Nuevo León');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (20, 'contacto.corpo@gesco-pls.com', null, 'Oaxaca');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (21, 'contacto.corpo@gesco-pls.com', null, 'Puebla');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (22, 'contacto.qro@gesco-pls.com', 'contacto.corpo@gesco-pls.com','Querétaro');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (23, 'contacto.cancun@gesco-pls.com', 'contacto.corpo@gesco-pls.com', 'Quintana Roo');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (24, 'contacto.corpo@gesco-pls.com', null, 'San Luis Potosí');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (25, 'contacto.corpo@gesco-pls.com', null, 'Sinaloa');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (26, 'contacto.corpo@gesco-pls.com', null, 'Sonora');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (27, 'contacto.corpo@gesco-pls.com', null, 'Tabasco');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (28, 'contacto.corpo@gesco-pls.com', null, 'Tamaulipas');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (29, 'contacto.corpo@gesco-pls.com', null, 'Tlaxcala');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (30, 'contacto.corpo@gesco-pls.com', null, 'Veracruz');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (31, 'contacto.corpo@gesco-pls.com', null, 'Yucatán');
insert into estados_correos (`id_estado_correo`, `correo_principal`, `correo_secundario`, `nombre`)  values (32, 'contacto.corpo@gesco-pls.com', null, 'Zacatecas');

insert into tipos_pagos (id_tipo_pago, name, descripction, langg, activo) values (1, 'CUOTA', 'Cuota Mensual', 'es', true);
insert into tipos_pagos (id_tipo_pago, name, descripction, langg, activo) values (2, 'RESERVA', 'Pago por reserva de área común', 'es', true);
insert into tipos_pagos (id_tipo_pago, name, descripction, langg, activo) values (3, 'OTRO', 'Otro pago', 'es', true);
insert into tipos_pagos (id_tipo_pago, name, descripction, langg, activo) values (4, 'CUOTA', 'Maintenance fee', 'en', true);
insert into tipos_pagos (id_tipo_pago, name, descripction, langg, activo) values (5, 'RESERVA', 'Reserve payment', 'en', true);
insert into tipos_pagos (id_tipo_pago, name, descripction, langg, activo) values (6, 'OTRO', 'Other payments', 'en', true);

insert into tipos_pagos_bancarios (id_tipo_pago_bancario, name, descripction, lang, activo) values (1, 'TRANSFERENCIA', 'Pago con transferencia bancaria o cheque', 'es', true);
insert into tipos_pagos_bancarios (id_tipo_pago_bancario, name, descripction, lang, activo) values (2, 'PAYPAL', 'Pago con Paypal', 'es', true);
insert into tipos_pagos_bancarios (id_tipo_pago_bancario, name, descripction, lang, activo) values (3, 'TARJETA', 'Pago con tarjeta', 'es', true);
insert into tipos_pagos_bancarios (id_tipo_pago_bancario, name, descripction, lang, activo) values (4, 'TRANSFERENCIA', 'Bank transfer or check payment', 'en', true);
insert into tipos_pagos_bancarios (id_tipo_pago_bancario, name, descripction, lang, activo) values (5, 'PAYPAL', 'Paypal payment', 'en', true);
insert into tipos_pagos_bancarios (id_tipo_pago_bancario, name, descripction, lang, activo) values (6, 'TARJETA', 'Credit card payment', 'en', true);

insert into estatus_pagos (id_estatus_pago, name, descripction, lang, activo) values (1, 'PAGADO', 'Pagado', 'es', true);
insert into estatus_pagos (id_estatus_pago, name, descripction, lang, activo) values (2, 'CERCANO', 'Pendiente de pago', 'es', true);
insert into estatus_pagos (id_estatus_pago, name, descripction, lang, activo) values (3, 'VERIFICACION', 'Verificando', 'es', true);
insert into estatus_pagos (id_estatus_pago, name, descripction, lang, activo) values (4, 'ATRASADO', 'Atrasado', 'es', true);
insert into estatus_pagos (id_estatus_pago, name, descripction, lang, activo) values (5, 'PAGADO', 'Paid', 'en', true);
insert into estatus_pagos (id_estatus_pago, name, descripction, lang, activo) values (6, 'CERCANO', 'Outstanding', 'en', true);
insert into estatus_pagos (id_estatus_pago, name, descripction, lang, activo) values (7, 'VERIFICACION', 'Verifying', 'en', true);
insert into estatus_pagos (id_estatus_pago, name, descripction, lang, activo) values (8, 'ATRASADO', 'Overdue', 'en', true);

insert into tipos_socios (id_tipo_socio, name, descripction, lang, activo) values (1, 'CONDOMINO', 'Condómino (propietario)', 'es', true);
insert into tipos_socios (id_tipo_socio, name, descripction, lang, activo) values (2, 'RESIDENTE', 'Residente (Arrendatario)', 'es', true);
insert into tipos_socios (id_tipo_socio, name, descripction, lang, activo) values (3, 'CONDOMINO', 'Condominium (owner)', 'en', true);
insert into tipos_socios (id_tipo_socio, name, descripction, lang, activo) values (4, 'RESIDENTE', 'Resident (Tenant)', 'en', true);

insert into meses (id_mes, descripcion, lang) values (1, 'Enero', 'es');
insert into meses (id_mes, descripcion, lang) values (2, 'Febrero', 'es');
insert into meses (id_mes, descripcion, lang) values (3, 'Marzo', 'es');
insert into meses (id_mes, descripcion, lang) values (4, 'Abril', 'es');
insert into meses (id_mes, descripcion, lang) values (5, 'Mayo', 'es');
insert into meses (id_mes, descripcion, lang) values (6, 'Junio', 'es');
insert into meses (id_mes, descripcion, lang) values (7, 'Julio', 'es');
insert into meses (id_mes, descripcion, lang) values (8, 'Agosto', 'es');
insert into meses (id_mes, descripcion, lang) values (9, 'Septiembre', 'es');
insert into meses (id_mes, descripcion, lang) values (10, 'Octubre', 'es');
insert into meses (id_mes, descripcion, lang) values (11, 'Noviembre', 'es');
insert into meses (id_mes, descripcion, lang) values (12, 'Diciembre', 'es');
insert into meses (id_mes, descripcion, lang) values (13, 'January', 'en');
insert into meses (id_mes, descripcion, lang) values (14, 'February', 'en');
insert into meses (id_mes, descripcion, lang) values (15, 'March', 'en');
insert into meses (id_mes, descripcion, lang) values (16, 'April', 'en');
insert into meses (id_mes, descripcion, lang) values (17, 'May', 'en');
insert into meses (id_mes, descripcion, lang) values (18, 'June', 'en');
insert into meses (id_mes, descripcion, lang) values (19, 'July', 'en');
insert into meses (id_mes, descripcion, lang) values (20, 'August', 'en');
insert into meses (id_mes, descripcion, lang) values (21, 'September', 'en');
insert into meses (id_mes, descripcion, lang) values (22, 'October', 'en');
insert into meses (id_mes, descripcion, lang) values (23, 'November', 'en');
insert into meses (id_mes, descripcion, lang) values (24, 'December', 'en');

insert into tipos_reporte_mensual (id_tipo_reporte_mensual, descripcion, lang, activo) values (1, 'Estados financieros', 'es', true);
insert into tipos_reporte_mensual (id_tipo_reporte_mensual, descripcion, lang, activo) values (2, 'Balance general', 'es', true);
insert into tipos_reporte_mensual (id_tipo_reporte_mensual, descripcion, lang, activo) values (3, 'Estado de resultados', 'es', true);
insert into tipos_reporte_mensual (id_tipo_reporte_mensual, descripcion, lang, activo) values (4, 'Egresos e ingresos', 'es', true);
insert into tipos_reporte_mensual (id_tipo_reporte_mensual, descripcion, lang, activo) values (5, 'Deudores', 'es', true);
insert into tipos_reporte_mensual (id_tipo_reporte_mensual, descripcion, lang, activo) values (6, 'Financial statements', 'en', true);
insert into tipos_reporte_mensual (id_tipo_reporte_mensual, descripcion, lang, activo) values (7, 'Balance sheet', 'en', true);
insert into tipos_reporte_mensual (id_tipo_reporte_mensual, descripcion, lang, activo) values (8, 'Statement of income', 'en', true);
insert into tipos_reporte_mensual (id_tipo_reporte_mensual, descripcion, lang, activo) values (9, 'Expenses and income', 'en', true);
insert into tipos_reporte_mensual (id_tipo_reporte_mensual, descripcion, lang, activo) values (10, 'Defaulters', 'en', true);

